#! /bin/sh
#
# Remove 'nearby' stations' instrument response.
#
# Each trace has its mean removed, then its trend removed, then it is
# is tapered, then deconvolved between freq limits, then multiplied by
# 1.0e9 to convert from M to NM (former the SEED convention from which
# these PZ files written, the latter the SAC convention that writes
# the output files with the adjusted headers).
#
# The multiplication is necessary because SAC does not look at the
# header comments concerning the amplitude unit -- you have to do that
# yourself (see "PZ EXAMPLES", pg. 7 of TRANSFER.pdf).
#
# Input:
# (1) directory containing SAC files (see fetchnearbytraces.m)
#     (e.g., $MERMAID/events/nearbystations/sac/10932551)
# (2) pole-zero filename (see fetchnearbypz.m)
#     (e.g., $MERMAID/events/nearbystations/pz/nearbystations.pz)
# (3) output type: none, vel, or acc (see 'transfer' in SAC manual)
# (4-7) array of freqlimits, in Hz: e.g., 0.001 0.01 1 10
#
# Output:
# SAC files with their instrument response removed, with the
# appropriate output type appended to their filenames.
#
# The input pole-zero file is assumed to contain the instrument
# response for all trace(s) supplied (i.e., it is a concatenation of
# all pole-zero files for each individual station/channel/location
# etc.).  See fetchnearbypz.m, which creates this file automatically.
#
# Author: Joel D. Simon
# Contact: jdsimon@princeton.edu
# Last modified: 07-Feb-2020

# Parse inputs.
sacdir=$1
pzfile=$2
otype=$3
fl1=$4
fl2=$5
fl3=$6
fl4=$7

# Make note of starting directory.
stardir=pwd;
cd $sacdir

# Read entire SAC directory and transfer.
sac << !
r $sacdir/*.SAC
rmean
rtr
taper
transfer from polezero subtype $pzfile to $otype freqlimits $fl1 $fl2 $fl3 $fl4
mul 1.0e9
w append .$otype
q
!

# Return to start directory.
cd $startdir
