#! /bin/sh
# Author: Joel D. Simon
# Contact: jdsimon@princeton.edu
# Last modified: 16-Nov-2019

net=$1
sta=$2
xml=$net.$sta.xml
sacpz=$net.$sta.sacpz

# This activates the MERMAID python environment which includes the necessary obspy package.
source activate pymaid

# This fetches a station.xml response file.
wget "https://fdsnws.raspberryshakedata.com/fdsnws/station/1/query?network=$net&station=$sta&level=resp&start=2018-06-01T01:01:01&format=xml" -O $xml

# This converts the station.xml respone file to a poles and zeros file for SAC.
python $OMNIA/earthquakes/xml2sacpz.py $xml

# This removes the fractional seconds and 'Z' from the datetimes, which SAC transfer cannot parse.
sed -i 's/\..*Z//' $sacpz

# This replaces the 'None' 'END' datetime, which SAC transfer cannot
# parse, with the default 'END' datetime returned by
# http://service.iris.edu/irisws/sacpz/1/query?
sed -i 's/None/2599-12-31T23:59:59/' $sacpz

# This exits the MERMAID python environment.
source deactivate

