#! /bin/sh
#
# Fetches and writes Raspberry Shake pole-zero files
# (all locations*, all Z channels) starting from 2018-06-01T01:01:01.
#
# Input: station abbreviation (e.g., R06CD)
# Output: AM.[station].Z.pz
#
# This function requires Python 2.7 and obspy and thus is not intended
# to be called separately but rather wrapped into, e.g.,
# fetchnearbypz.m.
#
# Raspberry Shake response data is only (so far as I can tell)
# returned as station.xml (and possibly SEED?) files, not the
# classical SAC pole-zero files.  At the very least (at the time of
# initial writing in Nov. 2019) they are not queryable from
# http://service.iris.edu/irisws/sacpz/1/.  This script takes an xml
# file and converts it to a pole-zero file, which necessitates a call
# to xml2pz.m (which it expects to find in $MERMAID/earthquakes), as
# well as some minor post-processing of the resultant pz file to cut
# off extra info ('Z', for UTC in datetimes), which SAC does not like.
#
# *N.B.: Raspberry stations only use location '00' --
#        https://manual.raspberryshake.org/stationNamingConvention.html
#        Regardless, I still wildcard the location parameter.
#
# Author: Joel D. Simon
# Contact: jdsimon@princeton.edu
# Last modified: 04-Mar-2020, Python 2.7.15 (pymaid env.)

# Input.
sta=$1

# Output.
xml=AM.$sta.Z.xml
pz=AM.$sta.Z.pz

# This fetches a station.xml response file.
wget "https://fdsnws.raspberryshakedata.com/fdsnws/station/1/query?network=AM&station=$sta&location=*&channel=*Z&level=response&start=2018-06-01T01:01:01&format=xml" -O $xml

# This converts the station.xml response file to a poles and zeros file for SAC.
python $OMNIA/earthquakes/xml2pz.py $xml

# This removes the fractional seconds and 'Z' from the datetimes,
# which SAC transfer cannot parse.
sed -i 's/\..*Z//' $pz

# This replaces the 'None' END datetime, which SAC transfer cannot
# parse, with the default '2599-12-31T23:59:59' END datetime returned
# by http://service.iris.edu/irisws/pz/1/query?
sed -i 's/None/2599-12-31T23:59:59/' $pz
