function MERMAID = read_tomocat1(filename)
% MERMAID = READ_UPDATE_SIMON2021GJI_SUPPLEMENT_RESIDUALS(filename)
%
% Input:
% filename   Filename to updated residual formatted text file
%                (def: $MERMAID/events/reviewed/identified/txt/tomocat1.txt)
%
% Output:
% MERMAID    Structure with fieldnames that which mirror the columns in the text file
%
% Author: Joel D. Simon
% Contact: jdsimon@princeton.edu | joeldsimon@gmail.com
% Last modified: 20-Nov-2023, Version 9.3.0.713579 (R2017b) on GLNXA64

defval('filename', fullfile(getenv('MERMAID'), 'events', 'reviewed', 'identified', 'txt', 'tomocat1.txt'))

fid = fopen(filename, 'r');
C = textscan(fid, ...
             ['%s' ...
              '%s' ...
              '%.4f' ...
              '%.4f' ...
              '%.1f' ...
              '%s' ...
              '%f' ...
              '%s' ...
              '%.4f' ...
              '%.4f' ...
              '%f' ...
              '%f' ...
              '%.4f' ...
              '%f' ...
              '%.4f' ...
              '%.4f' ...
              '%.4f' ...
              '%.2f' ...
              '%.2f' ...
              '%.2f' ...
              '%.2f' ...
              '%.2f' ...
              '%.2f' ...
              '%.2f' ...
              '%.2f' ...
              '%.2f' ...
              '%f' ...
              '%.2f' ...
              '%.2f' ...
              '%.2f' ...
              '%.2f' ...
              '%.2f' ...
              '%f' ...
              '%.2f' ...
              '%s' ...
              '%s', ...
              '%s', ...
              '%s', ...
              '%d\n'], ...
             'HeaderLines', 2, ...
             'Delimiter', ' ', ...
             'MultipleDelimsAsOne', true);
fclose(fid);

MERMAID.filename  = C{1};
MERMAID.event_time = C{2};
MERMAID.evlo = C{3}; % -180:180 longitude
MERMAID.evlo_360 = MERMAID.evlo;
MERMAID.evlo_360(MERMAID.evlo_360<0) = MERMAID.evlo(MERMAID.evlo_360<0) + 360; % 0:360 longitude
MERMAID.evla = C{4};
MERMAID.mag_val = C{5};
MERMAID.mag_type = C{6};
MERMAID.evdp = C{7};
MERMAID.seismogram_time = C{8};
MERMAID.stlo = C{9}; % -180:180 longitude
MERMAID.stlo_360 = MERMAID.stlo;
MERMAID.stlo_360(MERMAID.stlo_360<0) = MERMAID.stlo(MERMAID.stlo_360<0) + 360; % 0:360 longitude
MERMAID.stla = C{10};
MERMAID.stdp = C{11};
MERMAID.ocpd = C{12};
MERMAID.gcarc_1D = C{13};
MERMAID.gcarc_1Dstar_adj = C{14};
MERMAID.gcarc_1Dstar = C{15};
MERMAID.gcarc_3D_adj = C{16};
MERMAID.gcarc_3D = C{17};
MERMAID.obs_travtime = C{18};
MERMAID.obs_arvltime = C{19};
MERMAID.travtime_1D = C{20};
MERMAID.arvltime_1D = C{21};
MERMAID.tres_1D = C{22};
MERMAID.travtime_1Dstar_adj = C{23};
MERMAID.travtime_1Dstar = C{24};
MERMAID.arvltime_1Dstar = C{25};
MERMAID.tres_1Dstar = C{26};
MERMAID.travtime_3D_adj = C{27};
MERMAID.travtime_3D = C{28};
MERMAID.arvltime_3D = C{29};
MERMAID.tres_3D = C{30};
MERMAID.twosd = C{31};
MERMAID.SNR = C{32};
MERMAID.max_counts = C{33};
MERMAID.max_delay = C{34};
MERMAID.NEIC_ID = C{35};
MERMAID.IRIS_ID = C{36};
MERMAID.KSTNM = C{37};
MERMAID.phase_name = C{38};
MERMAID.reviewer = double(C{39});
