#!/bin/csh
#
# Counts MERMAID .evt files.
#
# Author: Joel D. Simon
# Contact: jdsimon@princeton.edu
# Last modified: 04-Oct-2019

set MERMAID = $MERMAID

# Count only Princeton SAC files
set floatnum = (08 09 10 11 12 13 16 17 18 19 20 21 22 23 24 25)
set evt_count = 0
set allevt = `find $MERMAID/events/reviewed -iname '*.evt'`
set idevt = `find $MERMAID/events/reviewed/identified -iname '*.evt'`
set nullevt = `find $MERMAID/events/reviewed/unidentified -iname '*.evt'`

printf "\n             All          ID    DET_ID    REQ_ID      NULL  DET_NULL  REQ_NULL\n"
foreach float ($floatnum[*])
    # This tallies all the .evt files.
    ls $allevt | awk '/'\.$float\_'/' > $MERMAID/temp
    set total = `cat $MERMAID/temp | wc -l`
    set det =  `grep .DET. $MERMAID/temp  | wc -l`
    set req =  `grep .REQ. $MERMAID/temp  | wc -l`
    rm $MERMAID/temp

    @ total_count += $total
    @ det_count += $det
    @ req_count += $req

    # This tallies the identified .evt files.
    ls $idevt | awk '/'\.$float\_'/' > $MERMAID/temp
    set id = `cat $MERMAID/temp | wc -l`
    set det_id = `grep .DET. $MERMAID/temp  | wc -l`
    set req_id = `grep .REQ. $MERMAID/temp  | wc -l`
    rm $MERMAID/temp

    @ total_id += $id
    @ total_det_id += $det_id
    @ total_req_id += $req_id


    # This tallies the unidentified .evt files.
    ls $nullevt | awk '/'\.$float\_'/' > $MERMAID/temp
    set null = `cat $MERMAID/temp | wc -l`
    set det_null = `grep .DET. $MERMAID/temp  | wc -l`
    set req_null = `grep .REQ. $MERMAID/temp  | wc -l`
    rm $MERMAID/temp

    @ total_null += $null
    @ total_det_null += $det_null
    @ total_req_null += $req_null

    printf "Float %s : %5i   |   %5i     %5i     %5i  |  %5i     %5i     %5i\n" $float $total $id $det_id $req_id $null $det_null $req_null

end
printf "------------------------------------------------------------------------------\n"
printf "Total :    %5i   |   %5i     %5i     %5i  |  %5i     %5i     %5i\n\n" $total_count $total_id $total_det_id $total_req_id $total_null $total_det_null $total_req_null
