#!/bin/tcsh -f
#
# Returns the date of the last .sac file associated with each float.
#
# Assumes all SAC files live in $MERMAID/processed.
#
# Author: Joel D. Simon
# Contact: jdsimon@princeton.edu
# Last modified: 21-Aug-2019

set floatnum = (08 09 10 11 12 13 16 17 18 19 20 21 22 23 24 25)

# OSX does not have the standard date formatting commands.  Must use a
# psuedo-swtich statment.  Redirect any error to the /dev/null/ to
# suppress output to stdout and check if it failed. On a proper Linux
# machine ths will display as '01-Jan-0001'; in Mac terminal it breaks.
date -d 00010101 +'%d-%b-%Y' >& /dev/null
if ( $? == 0 ) then
    set osx = 0
else
    set osx = 1
endif

foreach float ($floatnum[*])
    set perfloat = `ls -1 $MERMAID/processed/*P-$float*/*/*.sac | tail -1`
    set lasttime = `basename $perfloat | awk '{print substr($0,1,8)}'` 
    if ( $osx == 0) then
        set lastdate = `date -d $lasttime +'%d-%b-%Y'`
    else
	set lastdate = `date -jf "%Y%m%d" $lasttime +"%d-%b-%Y"`
    endif
    printf "Float %s : %s\n" $float $lastdate
end
