#! /bin/zsh
#
# Print date of last surfacing for each Princeton MERMAID, as read from ESO
# website textfile.
#
# Author: Joel D. Simon
# Contact: jdsimon@princeton.edu
# Last modified: 18-Jun-2020

computer=$(uname -s)

if [ $computer = Linux ]; then
    # The output filename (hyphen) means print to stdout. 
    dates=$(wget -qO - 'http://geoweb.princeton.edu/people/simons/SOM/all.txt')

elif [ $computer = Darwin ]; then
    dates=$(curl -s 'http://geoweb.princeton.edu/people/simons/SOM/all.txt')

else
    echo "Error: lastsurface script only tested on Linux and Mac computers"
    exit 1

fi
printf 'Last surfacing:\n'
echo $dates | sed -n '08,23p' | awk '{print $1,$2}'
