#! /bin/zsh
# Usage: merlog2date [file]
#
# Print UTC time, in ISO 8601 format, of UNIX Epoch time in .MER or .LOG
# file name, represented there as hex string.
#
# Examples:
#    merlog2date 10_5F3F99FF.LOG
#    merlog2date 10_5F4444FC.MER
#
# Author: Dr. Joel D. Simon
# Contact: jdsimon@alumni.princeton.edu | joeldsimon@gmail.com
# Last modified: 04-Sep-2020, Darwin Kernel Version 18.7.0

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    sed -ne '/^#/!q;s/^#$/# /;/^# /s/^# //p' < "$0" |
	awk -v f="${1#-h}" '!f && /^Usage:/ || u { u=!/^\s*$/; if (!u) exit } u || f'
    exit 1
fi

fname_no_ext="${1%.*}"
hextime=$(cut -d'_' -f2 <<< $fname_no_ext)
dectime=$(( 16#$hextime ))

computer=$(uname -s)
fmt=+%Y-%m-%dT%H:%M:%SZ

if [ $computer = Linux ]; then
    date -ud @$dectime $fmt

elif [ $computer = Darwin ]; then
    date -ur $dectime $fmt

else
    echo "Error: $0 only tested on Linux and Mac computers"
    exit 1

fi
