#!/bin/sh
#
# Simple shell script to:
# 1) retrieve MERMAID data
# 2) write new SAC (.sac) files
# 3) write changepoint (.cp) files with uncertainty estimates 
# 4) generate preliminary match to the seismic catalog and write
#    corresponding .evt and .pdf files
#
# No I/0 and requires internal editing as it was built for JDS' system
# defaults.
#
# Author: Joel D. Simon
# Contact: jdsimon@princeton.edu
# Last modified: 26-Mar-2019.

# Keep track of starting directory.
start_dir=`pwd`

# Pull most recent data.
echo -e 'Copying server...\n'
~/github/omnia/mermaid/servercopy
echo -e '\n...completed server copy\n'

# Generate SAC files.
echo -e 'Writing SAC files...\n'
cd $MERMAID
source activate pymaid
python scripts/main.py
source deactivate 
echo -e '\n...completed writing SAC files\n'

# Generate raw matches to the IRIS catalog.  Note that upon exiting
# MATLAB you may get the following message.
#
#    Identifier: 'MATLAB:connector:connector:ConnectorNotRunning'
#     Arguments: {}
#
# I have only noticed this since adding the parallel
# writechangepointall.m to matchall.m.  I assume it has something to
# do with MATLAB closing before the parallel pool is completely shut
# down.  Doesn't seem to affect the output of this code, however.
echo -e '\nMatching to the seismic catalog...\n'
/usr/local/MATLAB/R2017b/bin/matlab -nodisplay -r "run ~/github/omnia/mermaid/matchall.m; run exit"

# Display current count.
echo -e '\nHere is the complete list:\n'
$OMNIA/mermaid/countsac
echo 

# Return from whence you came.
/usr/bin/cd $start_dir
