#! /bin/zsh
# usage: osean2kinst [floatname]
#
# Return the "generic name of recording instrument" (KINST), defined as the
# string which precedes the first hyphen in the Osean-defined names.
#
# 452.112-N-01:   kinst = '452.112'
# 452.020-P-08:   kinst = '452.020'
# 452.020-P-0050: kinst = '452.020'
#
# Shell-script version of Dive.attach_kstnm_kinst() in automaid.
#
# Station names may be a max of five characters:
# https://ds.iris.edu/ds/newsletter/vol1/no1/1/specification-of-seismograms-the-location-identifier/
#
# example: osean2kinst 452.020-P-06
#
# Author: Joel D. Simon
# Contact: jdsimon@alumni.princeton.edu | joeldsimon@gmail.com
# Last modified: 09-Sep-2021, Darwin Kernel Version 18.7.0

# 452.020-P-06 --> 452.020
if [[ $# -eq 0 ]]; then
    echo "Error: no arguments supplied"
    return 0

else
    osean=$1

fi

split_name=("${(@s/-/)osean}")
kinst=$split_name[1]
printf '%s\n' $kinst
return 0
