#! /bin/zsh
#
# Return the five-character station name (KSTNM), zero-padded between the letter
# and number defining the unique MERMAID (if required) --
#
# 452.112-N-01:   kstnm = 'N0001'
# 452.020-P-08:   kstnm = 'P0008'
# 452.020-P-0050: kstnm = 'P0050'
#
# Shell-script version of Dive.attach_kstnm_kinst() in automaid.
#
# Station names may be a max of five characters:
# https://ds.iris.edu/ds/newsletter/vol1/no1/1/specification-of-seismograms-the-location-identifier/
#
# Author: Joel D. Simon
# Contact: jdsimon@alumni.princeton.edu | joeldsimon@gmail.com
# Last modified: 08-Sep-2021, Version 9.3.0.948333 (R2017b) Update 9 on MACI64

# 452.020-P-06 --> P0006
osean=$1
split_name=("${(@s/-/)osean}")
len_kstnm=$( echo -n $split_name[2]$split_name[3] | wc -m )
if [[ len_kstnm -gt 5 ]]; then
    echo "Unexpected input: kstnm greater than five characters"
    return 1

elif [[ len_kstnm -eq 5 ]]; then
    kstnm=$split_name[2]$split_name[3]

else
    len_zeropad=$(( 5 - len_kstnm ))
    zeros=$( printf '0%.0s' {1..$len_zeropad} )
    kstnm=$split_name[2]$zeros$split_name[3]

fi

printf '%s\n' $kstnm
return 0
