#! /bin/zsh
#
# Generate acqusition "started" and "stopped" logs in $MEMAID/processed.
#
# Author: Joel D. Simon
# Contact: jdsimon@alumni.princeton.edu | joeldsimon@gmail.com
# Last modified: 16-Aug-2022, Darwin Kernel Version 18.7.0

# Loop over all MERMAID subdirectories
# NB, the final forward slash ("/") is required here
proc_dir=$MERMAID/processed/
for mer_dir in $( ls -1d $proc_dir/*/ ); do
    # Grep "acq" line
    acq=$( grep --no-filename "acq" $mer_dir/**/*.LOG.h )

    # Define and unlock log file
    log=$mer_dir/acq_log.txt
    if [[ -f $log ]]; then
	chmod +w $log

    fi

    # Remove "[MRMAID,557]", "[MRMAID,594]", "already", and "acq"
    echo $acq | sed 's/:\[MRMAID,.*\]/ /g' | sed 's/already//g' | sed 's/acq //g' >! $log

    # Lock print log filename
    chmod -w $log
    printf "Wrote %s\n" $log

done
