#! /bin/zsh
#
# Generate `acq started`, `acq stopped` logs in $MEMAID/processed.
#
# Author: Joel D. Simon
# Contact: jdsimon@alumni.princeton.edu | joeldsimon@gmail.com
# Last modified: 28-Apr-2022, Darwin Kernel Version 18.7.0

# Loop over all MERMAID subdirectories
# NB, the final forward slash ("/") is required here
proc_dir=$MERMAID/processed/
for mer_dir in $( ls -1d $proc_dir/*/ ); do
    # Grep "acq" line
    acq=$( grep --no-filename "acq" $mer_dir/**/*.LOG.h )

    # Define and unlock log file
    log=$mer_dir/acq_log.txt
    chmod +w $log

    # Remove [MRMAID,557] and [MRMAID,594]
    echo $acq | sed 's/:\[MRMAID,.*\]/ /g' > $log

    # Lock print log filename
    chmod -w $log
    printf "Wrote %s\n" $log

done
