function writeiqoe(sac)
% WRITEIQOE(sac)
%
% Write MERMAID .xlsx file for International Quiet Ocean Experiment (IQOE) database.
%
% Input:
% sac      Array of SAC filenames
%
% Author: Joel D. Simon
% Contact: jdsimon@alumni.princeton.edu | joeldsimon@gmail.com
% Last modified: 08-May-2025, 24.1.0.2568132 (R2024a) Update 1 on MACA64 (geo_mac)

% Constant attributes.
public = 'Public';
contact = 'mermaid@princeton.edu';
cabled = 'autonomous';
freq_range = '0.1 - 10';
duty_cycle = 'Null';
hydrophone = 'High Tech HTI-96-Min Hex';
purpose = 'Mobile Earthquake Recording in Marine Areas by Independent Divers (MERMAID)';
acknowledge = 'doi: 10.7914/SN/MH';

% Date format
dfmt = 'uuuu-MM-dd HH:mm:ss.SS';

for i = 1:length(sac);
    % Get SAC header and determine station name and samp freq.
    h = sachdr(sac{i});
    kstnm = h.KSTNM;
    samp_freq(i) = efes(h, true);

    % Start/end lat/lon are the same.
    lat(i) = round(h.STLA, 3);
    lon(i) = round(h.STLO, 3);

    % Get start/end times.
    sd = seistime(h);
    start_date{i} = string(sd.B, dfmt);
    end_date{i} = string(sd.E, dfmt);

    % Get water depth (negative elevation) and deployment depth.
    ocdp(i) = -gebco(lon(i), lat(i));
    stdp(i) = h.STDP;

end

varnames = ["Public or Private", ...
            "Data Contact", ...
            "Cabled or Autonomous", ...
            "Start Lat", ...
            "Start Long", ...
            "End Lat", ...
            "End Long", ...
            "Start Date", ...
            "End of Deployment", ...
            "Freq. Range", ...
            "Sampling Freq. (Hz)", ...
            "Duty Cycle [min/hr]", ...
            "Hydrophone Type", ...
            "Water Depth", ...
            "Deployment Depth", ...
            "Purpose", ...
            "Acknowledgement/Paper Citation"];

T = table(repmat(public, size(lat')), ...
          repmat(contact, size(lat')), ...
          repmat(cabled, size(lat')), ...
          lat(:), ...
          lon(:), ...
          lat(:), ...
          lon(:), ...
          start_date(:), ...
          end_date(:), ...
          repmat(freq_range, size(lat')), ...
          samp_freq(:), ...
          repmat(duty_cycle, size(lat')), ...
          repmat(hydrophone, size(lat')), ...
          ocdp(:), ...
          stdp(:), ...
          repmat(purpose, size(lat')), ...
          repmat(acknowledge, size(lat')), ...
          'VariableNames', varnames);


% Write Excel sheet, overwritting any existing file.
xlsname = fullfile(pwd, 'iqoe_mermaid.xlsx');
writetable(T, xlsname, 'WriteMode', 'overwritesheet')
fprintf('Wrote %i records to:\n%s\n', length(sac), xlsname);
