function time2meet(meeting_day, their_timezone)
% TIME2MEET(meeting_day, their_timezone)
%
% Print collaborators' local times w.r.t. Joel's timezone ('America/Los_Angeles').
%
% !! WARNING: Note flipped convention of 'Etc/GMT-*' == 'UTC+*' !!
%
% Input:
% meeting_day      Date of proposed meeting, in Joel's timezone
%                      (datetime; def: datetime('today'))
% their_timezone   Collaborator's IANA timezone, listed below (char/string)
%
% Ex:
%    TIME2MEET(datetime('tomorrow'), 'Asia/Shanghai')
%    TIME2MEET(datetime('tomorrow'), 'Etc/GMT-14') % == UTC+14
%    TIME2MEET(datetime('tomorrow'), 'UTC+14') % == Etc/GMT-14
%
% Author: Joel D. Simon <jdsimon@bathymetrix.com>
% Last modified: 03-Nov-2025, 9.13.0.2553342 (R2022b) Update 9 on MACI64 (geo_mac)
% (in reality: Intel MATLAB in Rosetta 2 running on an Apple silicon Mac)
%
% IANA timezones (note that 'UTC+/-*' is also valid but not listed):
%
%           NAME                            AREA          UTCOffset   DSTOffset
%    {'Africa/Abidjan'                }    Africa              0           0
%    {'Africa/Accra'                  }    Africa              0           0
%    {'Africa/Addis_Ababa'            }    Africa              3           0
%    {'Africa/Algiers'                }    Africa              1           0
%    {'Africa/Asmera'                 }    Africa              3           0
%    {'Africa/Bamako'                 }    Africa              0           0
%    {'Africa/Bangui'                 }    Africa              1           0
%    {'Africa/Banjul'                 }    Africa              0           0
%    {'Africa/Bissau'                 }    Africa              0           0
%    {'Africa/Blantyre'               }    Africa              2           0
%    {'Africa/Brazzaville'            }    Africa              1           0
%    {'Africa/Bujumbura'              }    Africa              2           0
%    {'Africa/Cairo'                  }    Africa              2           0
%    {'Africa/Casablanca'             }    Africa              0           1
%    {'Africa/Ceuta'                  }    Africa              1           1
%    {'Africa/Conakry'                }    Africa              0           0
%    {'Africa/Dakar'                  }    Africa              0           0
%    {'Africa/Dar_es_Salaam'          }    Africa              3           0
%    {'Africa/Djibouti'               }    Africa              3           0
%    {'Africa/Douala'                 }    Africa              1           0
%    {'Africa/El_Aaiun'               }    Africa              0           1
%    {'Africa/Freetown'               }    Africa              0           0
%    {'Africa/Gaborone'               }    Africa              2           0
%    {'Africa/Harare'                 }    Africa              2           0
%    {'Africa/Johannesburg'           }    Africa              2           0
%    {'Africa/Juba'                   }    Africa              2           0
%    {'Africa/Kampala'                }    Africa              3           0
%    {'Africa/Khartoum'               }    Africa              2           0
%    {'Africa/Kigali'                 }    Africa              2           0
%    {'Africa/Kinshasa'               }    Africa              1           0
%    {'Africa/Lagos'                  }    Africa              1           0
%    {'Africa/Libreville'             }    Africa              1           0
%    {'Africa/Lome'                   }    Africa              0           0
%    {'Africa/Luanda'                 }    Africa              1           0
%    {'Africa/Lubumbashi'             }    Africa              2           0
%    {'Africa/Lusaka'                 }    Africa              2           0
%    {'Africa/Malabo'                 }    Africa              1           0
%    {'Africa/Maputo'                 }    Africa              2           0
%    {'Africa/Maseru'                 }    Africa              2           0
%    {'Africa/Mbabane'                }    Africa              2           0
%    {'Africa/Mogadishu'              }    Africa              3           0
%    {'Africa/Monrovia'               }    Africa              0           0
%    {'Africa/Nairobi'                }    Africa              3           0
%    {'Africa/Ndjamena'               }    Africa              1           0
%    {'Africa/Niamey'                 }    Africa              1           0
%    {'Africa/Nouakchott'             }    Africa              0           0
%    {'Africa/Ouagadougou'            }    Africa              0           0
%    {'Africa/Porto-Novo'             }    Africa              1           0
%    {'Africa/Sao_Tome'               }    Africa              0           0
%    {'Africa/Tripoli'                }    Africa              2           0
%    {'Africa/Tunis'                  }    Africa              1           0
%    {'Africa/Windhoek'               }    Africa              2           0
%    {'America/Adak'                  }    America           -10           1
%    {'America/Anchorage'             }    America            -9           1
%    {'America/Anguilla'              }    America            -4           0
%    {'America/Antigua'               }    America            -4           0
%    {'America/Araguaina'             }    America            -3           0
%    {'America/Argentina/La_Rioja'    }    America            -3           0
%    {'America/Argentina/Rio_Gallegos'}    America            -3           0
%    {'America/Argentina/Salta'       }    America            -3           0
%    {'America/Argentina/San_Juan'    }    America            -3           0
%    {'America/Argentina/San_Luis'    }    America            -3           0
%    {'America/Argentina/Tucuman'     }    America            -3           0
%    {'America/Argentina/Ushuaia'     }    America            -3           0
%    {'America/Aruba'                 }    America            -4           0
%    {'America/Asuncion'              }    America            -4           1
%    {'America/Bahia'                 }    America            -3           0
%    {'America/Bahia_Banderas'        }    America            -6           0
%    {'America/Barbados'              }    America            -4           0
%    {'America/Belem'                 }    America            -3           0
%    {'America/Belize'                }    America            -6           0
%    {'America/Blanc-Sablon'          }    America            -4           0
%    {'America/Boa_Vista'             }    America            -4           0
%    {'America/Bogota'                }    America            -5           0
%    {'America/Boise'                 }    America            -7           1
%    {'America/Buenos_Aires'          }    America            -3           0
%    {'America/Cambridge_Bay'         }    America            -7           1
%    {'America/Campo_Grande'          }    America            -4           0
%    {'America/Cancun'                }    America            -5           0
%    {'America/Caracas'               }    America            -4           0
%    {'America/Catamarca'             }    America            -3           0
%    {'America/Cayenne'               }    America            -3           0
%    {'America/Cayman'                }    America            -5           0
%    {'America/Chicago'               }    America            -6           1
%    {'America/Chihuahua'             }    America            -6           0
%    {'America/Coral_Harbour'         }    America            -5           0
%    {'America/Cordoba'               }    America            -3           0
%    {'America/Costa_Rica'            }    America            -6           0
%    {'America/Creston'               }    America            -7           0
%    {'America/Cuiaba'                }    America            -4           0
%    {'America/Curacao'               }    America            -4           0
%    {'America/Danmarkshavn'          }    America             0           0
%    {'America/Dawson'                }    America            -7           0
%    {'America/Dawson_Creek'          }    America            -7           0
%    {'America/Denver'                }    America            -7           1
%    {'America/Detroit'               }    America            -5           1
%    {'America/Dominica'              }    America            -4           0
%    {'America/Edmonton'              }    America            -7           1
%    {'America/Eirunepe'              }    America            -5           0
%    {'America/El_Salvador'           }    America            -6           0
%    {'America/Fort_Nelson'           }    America            -7           0
%    {'America/Fortaleza'             }    America            -3           0
%    {'America/Glace_Bay'             }    America            -4           1
%    {'America/Godthab'               }    America            -3           1
%    {'America/Goose_Bay'             }    America            -4           1
%    {'America/Grand_Turk'            }    America            -5           1
%    {'America/Grenada'               }    America            -4           0
%    {'America/Guadeloupe'            }    America            -4           0
%    {'America/Guatemala'             }    America            -6           0
%    {'America/Guayaquil'             }    America            -5           0
%    {'America/Guyana'                }    America            -4           0
%    {'America/Halifax'               }    America            -4           1
%    {'America/Havana'                }    America            -5           1
%    {'America/Hermosillo'            }    America            -7           0
%    {'America/Indiana/Knox'          }    America            -6           1
%    {'America/Indiana/Marengo'       }    America            -5           1
%    {'America/Indiana/Petersburg'    }    America            -5           1
%    {'America/Indiana/Tell_City'     }    America            -6           1
%    {'America/Indiana/Vevay'         }    America            -5           1
%    {'America/Indiana/Vincennes'     }    America            -5           1
%    {'America/Indiana/Winamac'       }    America            -5           1
%    {'America/Indianapolis'          }    America            -5           1
%    {'America/Inuvik'                }    America            -7           1
%    {'America/Iqaluit'               }    America            -5           1
%    {'America/Jamaica'               }    America            -5           0
%    {'America/Jujuy'                 }    America            -3           0
%    {'America/Juneau'                }    America            -9           1
%    {'America/Kentucky/Monticello'   }    America            -5           1
%    {'America/Kralendijk'            }    America            -4           0
%    {'America/La_Paz'                }    America            -4           0
%    {'America/Lima'                  }    America            -5           0
%    {'America/Los_Angeles'           }    America            -8           1
%    {'America/Louisville'            }    America            -5           1
%    {'America/Lower_Princes'         }    America            -4           0
%    {'America/Maceio'                }    America            -3           0
%    {'America/Managua'               }    America            -6           0
%    {'America/Manaus'                }    America            -4           0
%    {'America/Marigot'               }    America            -4           0
%    {'America/Martinique'            }    America            -4           0
%    {'America/Matamoros'             }    America            -6           1
%    {'America/Mazatlan'              }    America            -7           0
%    {'America/Mendoza'               }    America            -3           0
%    {'America/Menominee'             }    America            -6           1
%    {'America/Merida'                }    America            -6           0
%    {'America/Metlakatla'            }    America            -9           1
%    {'America/Mexico_City'           }    America            -6           0
%    {'America/Miquelon'              }    America            -3           1
%    {'America/Moncton'               }    America            -4           1
%    {'America/Monterrey'             }    America            -6           0
%    {'America/Montevideo'            }    America            -3           0
%    {'America/Montreal'              }    America            -5           1
%    {'America/Montserrat'            }    America            -4           0
%    {'America/Nassau'                }    America            -5           1
%    {'America/New_York'              }    America            -5           1
%    {'America/Nipigon'               }    America            -5           1
%    {'America/Nome'                  }    America            -9           1
%    {'America/Noronha'               }    America            -2           0
%    {'America/North_Dakota/Beulah'   }    America            -6           1
%    {'America/North_Dakota/Center'   }    America            -6           1
%    {'America/North_Dakota/New_Salem'}    America            -6           1
%    {'America/Ojinaga'               }    America            -6           0
%    {'America/Panama'                }    America            -5           0
%    {'America/Pangnirtung'           }    America            -5           1
%    {'America/Paramaribo'            }    America            -3           0
%    {'America/Phoenix'               }    America            -7           0
%    {'America/Port-au-Prince'        }    America            -5           1
%    {'America/Port_of_Spain'         }    America            -4           0
%    {'America/Porto_Velho'           }    America            -4           0
%    {'America/Puerto_Rico'           }    America            -4           0
%    {'America/Punta_Arenas'          }    America            -3           0
%    {'America/Rainy_River'           }    America            -6           1
%    {'America/Rankin_Inlet'          }    America            -6           1
%    {'America/Recife'                }    America            -3           0
%    {'America/Regina'                }    America            -6           0
%    {'America/Resolute'              }    America            -6           1
%    {'America/Rio_Branco'            }    America            -5           0
%    {'America/Santa_Isabel'          }    America            -8           1
%    {'America/Santarem'              }    America            -3           0
%    {'America/Santiago'              }    America            -4           1
%    {'America/Santo_Domingo'         }    America            -4           0
%    {'America/Sao_Paulo'             }    America            -3           0
%    {'America/Scoresbysund'          }    America            -1           1
%    {'America/Sitka'                 }    America            -9           1
%    {'America/St_Barthelemy'         }    America            -4           0
%    {'America/St_Johns'              }    America          -3.5           1
%    {'America/St_Kitts'              }    America            -4           0
%    {'America/St_Lucia'              }    America            -4           0
%    {'America/St_Thomas'             }    America            -4           0
%    {'America/St_Vincent'            }    America            -4           0
%    {'America/Swift_Current'         }    America            -6           0
%    {'America/Tegucigalpa'           }    America            -6           0
%    {'America/Thule'                 }    America            -4           1
%    {'America/Thunder_Bay'           }    America            -5           1
%    {'America/Tijuana'               }    America            -8           1
%    {'America/Toronto'               }    America            -5           1
%    {'America/Tortola'               }    America            -4           0
%    {'America/Vancouver'             }    America            -8           1
%    {'America/Whitehorse'            }    America            -7           0
%    {'America/Winnipeg'              }    America            -6           1
%    {'America/Yakutat'               }    America            -9           1
%    {'America/Yellowknife'           }    America            -7           1
%    {'Antarctica/Casey'              }    Antarctica         11           0
%    {'Antarctica/Davis'              }    Antarctica          7           0
%    {'Antarctica/DumontDUrville'     }    Antarctica         10           0
%    {'Antarctica/Macquarie'          }    Antarctica         10           1
%    {'Antarctica/Mawson'             }    Antarctica          5           0
%    {'Antarctica/McMurdo'            }    Antarctica         12           1
%    {'Antarctica/Palmer'             }    Antarctica         -3           0
%    {'Antarctica/Rothera'            }    Antarctica         -3           0
%    {'Antarctica/Syowa'              }    Antarctica          3           0
%    {'Antarctica/Troll'              }    Antarctica          0           2
%    {'Antarctica/Vostok'             }    Antarctica          6           0
%    {'Arctic/Longyearbyen'           }    Arctic              1           1
%    {'Asia/Aden'                     }    Asia                3           0
%    {'Asia/Almaty'                   }    Asia                6           0
%    {'Asia/Amman'                    }    Asia                3           0
%    {'Asia/Anadyr'                   }    Asia               12           0
%    {'Asia/Aqtau'                    }    Asia                5           0
%    {'Asia/Aqtobe'                   }    Asia                5           0
%    {'Asia/Ashgabat'                 }    Asia                5           0
%    {'Asia/Atyrau'                   }    Asia                5           0
%    {'Asia/Baghdad'                  }    Asia                3           0
%    {'Asia/Bahrain'                  }    Asia                3           0
%    {'Asia/Baku'                     }    Asia                4           0
%    {'Asia/Bangkok'                  }    Asia                7           0
%    {'Asia/Barnaul'                  }    Asia                7           0
%    {'Asia/Beirut'                   }    Asia                2           1
%    {'Asia/Bishkek'                  }    Asia                6           0
%    {'Asia/Brunei'                   }    Asia                8           0
%    {'Asia/Calcutta'                 }    Asia              5.5           0
%    {'Asia/Chita'                    }    Asia                9           0
%    {'Asia/Choibalsan'               }    Asia                8           0
%    {'Asia/Colombo'                  }    Asia              5.5           0
%    {'Asia/Damascus'                 }    Asia                3           0
%    {'Asia/Dhaka'                    }    Asia                6           0
%    {'Asia/Dili'                     }    Asia                9           0
%    {'Asia/Dubai'                    }    Asia                4           0
%    {'Asia/Dushanbe'                 }    Asia                5           0
%    {'Asia/Famagusta'                }    Asia                2           1
%    {'Asia/Gaza'                     }    Asia                2           1
%    {'Asia/Hebron'                   }    Asia                2           1
%    {'Asia/Hong_Kong'                }    Asia                8           0
%    {'Asia/Hovd'                     }    Asia                7           0
%    {'Asia/Irkutsk'                  }    Asia                8           0
%    {'Asia/Jakarta'                  }    Asia                7           0
%    {'Asia/Jayapura'                 }    Asia                9           0
%    {'Asia/Jerusalem'                }    Asia                2           1
%    {'Asia/Kabul'                    }    Asia              4.5           0
%    {'Asia/Kamchatka'                }    Asia               12           0
%    {'Asia/Karachi'                  }    Asia                5           0
%    {'Asia/Katmandu'                 }    Asia             5.75           0
%    {'Asia/Khandyga'                 }    Asia                9           0
%    {'Asia/Krasnoyarsk'              }    Asia                7           0
%    {'Asia/Kuala_Lumpur'             }    Asia                8           0
%    {'Asia/Kuching'                  }    Asia                8           0
%    {'Asia/Kuwait'                   }    Asia                3           0
%    {'Asia/Macau'                    }    Asia                8           0
%    {'Asia/Magadan'                  }    Asia               11           0
%    {'Asia/Makassar'                 }    Asia                8           0
%    {'Asia/Manila'                   }    Asia                8           0
%    {'Asia/Muscat'                   }    Asia                4           0
%    {'Asia/Nicosia'                  }    Asia                2           1
%    {'Asia/Novokuznetsk'             }    Asia                7           0
%    {'Asia/Novosibirsk'              }    Asia                7           0
%    {'Asia/Omsk'                     }    Asia                6           0
%    {'Asia/Oral'                     }    Asia                5           0
%    {'Asia/Phnom_Penh'               }    Asia                7           0
%    {'Asia/Pontianak'                }    Asia                7           0
%    {'Asia/Pyongyang'                }    Asia                9           0
%    {'Asia/Qatar'                    }    Asia                3           0
%    {'Asia/Qostanay'                 }    Asia                6           0
%    {'Asia/Qyzylorda'                }    Asia                5           0
%    {'Asia/Rangoon'                  }    Asia              6.5           0
%    {'Asia/Riyadh'                   }    Asia                3           0
%    {'Asia/Saigon'                   }    Asia                7           0
%    {'Asia/Sakhalin'                 }    Asia               11           0
%    {'Asia/Samarkand'                }    Asia                5           0
%    {'Asia/Seoul'                    }    Asia                9           0
%    {'Asia/Shanghai'                 }    Asia                8           0
%    {'Asia/Singapore'                }    Asia                8           0
%    {'Asia/Srednekolymsk'            }    Asia               11           0
%    {'Asia/Taipei'                   }    Asia                8           0
%    {'Asia/Tashkent'                 }    Asia                5           0
%    {'Asia/Tbilisi'                  }    Asia                4           0
%    {'Asia/Tehran'                   }    Asia              3.5           0
%    {'Asia/Thimphu'                  }    Asia                6           0
%    {'Asia/Tokyo'                    }    Asia                9           0
%    {'Asia/Tomsk'                    }    Asia                7           0
%    {'Asia/Ulaanbaatar'              }    Asia                8           0
%    {'Asia/Urumqi'                   }    Asia                6           0
%    {'Asia/Ust-Nera'                 }    Asia               10           0
%    {'Asia/Vientiane'                }    Asia                7           0
%    {'Asia/Vladivostok'              }    Asia               10           0
%    {'Asia/Yakutsk'                  }    Asia                9           0
%    {'Asia/Yekaterinburg'            }    Asia                5           0
%    {'Asia/Yerevan'                  }    Asia                4           0
%    {'Atlantic/Azores'               }    Atlantic           -1           1
%    {'Atlantic/Bermuda'              }    Atlantic           -4           1
%    {'Atlantic/Canary'               }    Atlantic            0           1
%    {'Atlantic/Cape_Verde'           }    Atlantic           -1           0
%    {'Atlantic/Faeroe'               }    Atlantic            0           1
%    {'Atlantic/Madeira'              }    Atlantic            0           1
%    {'Atlantic/Reykjavik'            }    Atlantic            0           0
%    {'Atlantic/South_Georgia'        }    Atlantic           -2           0
%    {'Atlantic/St_Helena'            }    Atlantic            0           0
%    {'Atlantic/Stanley'              }    Atlantic           -3           0
%    {'Australia/Adelaide'            }    Australia         9.5           1
%    {'Australia/Brisbane'            }    Australia          10           0
%    {'Australia/Broken_Hill'         }    Australia         9.5           1
%    {'Australia/Currie'              }    Australia          10           1
%    {'Australia/Darwin'              }    Australia         9.5           0
%    {'Australia/Eucla'               }    Australia        8.75           0
%    {'Australia/Hobart'              }    Australia          10           1
%    {'Australia/Lindeman'            }    Australia          10           0
%    {'Australia/Lord_Howe'           }    Australia        10.5         0.5
%    {'Australia/Melbourne'           }    Australia          10           1
%    {'Australia/Perth'               }    Australia           8           0
%    {'Australia/Sydney'              }    Australia          10           1
%    {'Etc/GMT'                       }    Etc                 0           0
%    {'Etc/GMT+1'                     }    Etc                -1           0
%    {'Etc/GMT+10'                    }    Etc               -10           0
%    {'Etc/GMT+11'                    }    Etc               -11           0
%    {'Etc/GMT+12'                    }    Etc               -12           0
%    {'Etc/GMT+2'                     }    Etc                -2           0
%    {'Etc/GMT+3'                     }    Etc                -3           0
%    {'Etc/GMT+4'                     }    Etc                -4           0
%    {'Etc/GMT+5'                     }    Etc                -5           0
%    {'Etc/GMT+6'                     }    Etc                -6           0
%    {'Etc/GMT+7'                     }    Etc                -7           0
%    {'Etc/GMT+8'                     }    Etc                -8           0
%    {'Etc/GMT+9'                     }    Etc                -9           0
%    {'Etc/GMT-1'                     }    Etc                 1           0
%    {'Etc/GMT-10'                    }    Etc                10           0
%    {'Etc/GMT-11'                    }    Etc                11           0
%    {'Etc/GMT-12'                    }    Etc                12           0
%    {'Etc/GMT-13'                    }    Etc                13           0
%    {'Etc/GMT-14'                    }    Etc                14           0
%    {'Etc/GMT-2'                     }    Etc                 2           0
%    {'Etc/GMT-3'                     }    Etc                 3           0
%    {'Etc/GMT-4'                     }    Etc                 4           0
%    {'Etc/GMT-5'                     }    Etc                 5           0
%    {'Etc/GMT-6'                     }    Etc                 6           0
%    {'Etc/GMT-7'                     }    Etc                 7           0
%    {'Etc/GMT-8'                     }    Etc                 8           0
%    {'Etc/GMT-9'                     }    Etc                 9           0
%    {'Etc/UTC'                       }    Etc                 0           0
%    {'Europe/Amsterdam'              }    Europe              1           1
%    {'Europe/Andorra'                }    Europe              1           1
%    {'Europe/Astrakhan'              }    Europe              4           0
%    {'Europe/Athens'                 }    Europe              2           1
%    {'Europe/Belgrade'               }    Europe              1           1
%    {'Europe/Berlin'                 }    Europe              1           1
%    {'Europe/Bratislava'             }    Europe              1           1
%    {'Europe/Brussels'               }    Europe              1           1
%    {'Europe/Bucharest'              }    Europe              2           1
%    {'Europe/Budapest'               }    Europe              1           1
%    {'Europe/Busingen'               }    Europe              1           1
%    {'Europe/Chisinau'               }    Europe              2           1
%    {'Europe/Copenhagen'             }    Europe              1           1
%    {'Europe/Dublin'                 }    Europe              0           1
%    {'Europe/Gibraltar'              }    Europe              1           1
%    {'Europe/Guernsey'               }    Europe              0           1
%    {'Europe/Helsinki'               }    Europe              2           1
%    {'Europe/Isle_of_Man'            }    Europe              0           1
%    {'Europe/Istanbul'               }    Europe              3           0
%    {'Europe/Jersey'                 }    Europe              0           1
%    {'Europe/Kaliningrad'            }    Europe              2           0
%    {'Europe/Kiev'                   }    Europe              2           1
%    {'Europe/Kirov'                  }    Europe              3           0
%    {'Europe/Lisbon'                 }    Europe              0           1
%    {'Europe/Ljubljana'              }    Europe              1           1
%    {'Europe/London'                 }    Europe              0           1
%    {'Europe/Luxembourg'             }    Europe              1           1
%    {'Europe/Madrid'                 }    Europe              1           1
%    {'Europe/Malta'                  }    Europe              1           1
%    {'Europe/Mariehamn'              }    Europe              2           1
%    {'Europe/Minsk'                  }    Europe              3           0
%    {'Europe/Monaco'                 }    Europe              1           1
%    {'Europe/Moscow'                 }    Europe              3           0
%    {'Europe/Oslo'                   }    Europe              1           1
%    {'Europe/Paris'                  }    Europe              1           1
%    {'Europe/Podgorica'              }    Europe              1           1
%    {'Europe/Prague'                 }    Europe              1           1
%    {'Europe/Riga'                   }    Europe              2           1
%    {'Europe/Rome'                   }    Europe              1           1
%    {'Europe/Samara'                 }    Europe              4           0
%    {'Europe/San_Marino'             }    Europe              1           1
%    {'Europe/Sarajevo'               }    Europe              1           1
%    {'Europe/Saratov'                }    Europe              4           0
%    {'Europe/Simferopol'             }    Europe              3           0
%    {'Europe/Skopje'                 }    Europe              1           1
%    {'Europe/Sofia'                  }    Europe              2           1
%    {'Europe/Stockholm'              }    Europe              1           1
%    {'Europe/Tallinn'                }    Europe              2           1
%    {'Europe/Tirane'                 }    Europe              1           1
%    {'Europe/Ulyanovsk'              }    Europe              4           0
%    {'Europe/Uzhgorod'               }    Europe              2           1
%    {'Europe/Vaduz'                  }    Europe              1           1
%    {'Europe/Vatican'                }    Europe              1           1
%    {'Europe/Vienna'                 }    Europe              1           1
%    {'Europe/Vilnius'                }    Europe              2           1
%    {'Europe/Volgograd'              }    Europe              3           0
%    {'Europe/Warsaw'                 }    Europe              1           1
%    {'Europe/Zagreb'                 }    Europe              1           1
%    {'Europe/Zaporozhye'             }    Europe              2           1
%    {'Europe/Zurich'                 }    Europe              1           1
%    {'Indian/Antananarivo'           }    Indian              3           0
%    {'Indian/Chagos'                 }    Indian              6           0
%    {'Indian/Christmas'              }    Indian              7           0
%    {'Indian/Cocos'                  }    Indian            6.5           0
%    {'Indian/Comoro'                 }    Indian              3           0
%    {'Indian/Kerguelen'              }    Indian              5           0
%    {'Indian/Mahe'                   }    Indian              4           0
%    {'Indian/Maldives'               }    Indian              5           0
%    {'Indian/Mauritius'              }    Indian              4           0
%    {'Indian/Mayotte'                }    Indian              3           0
%    {'Indian/Reunion'                }    Indian              4           0
%    {'Pacific/Apia'                  }    Pacific            13           0
%    {'Pacific/Auckland'              }    Pacific            12           1
%    {'Pacific/Bougainville'          }    Pacific            11           0
%    {'Pacific/Chatham'               }    Pacific         12.75           1
%    {'Pacific/Easter'                }    Pacific            -6           1
%    {'Pacific/Efate'                 }    Pacific            11           0
%    {'Pacific/Enderbury'             }    Pacific            13           0
%    {'Pacific/Fakaofo'               }    Pacific            13           0
%    {'Pacific/Fiji'                  }    Pacific            12           0
%    {'Pacific/Funafuti'              }    Pacific            12           0
%    {'Pacific/Galapagos'             }    Pacific            -6           0
%    {'Pacific/Gambier'               }    Pacific            -9           0
%    {'Pacific/Guadalcanal'           }    Pacific            11           0
%    {'Pacific/Guam'                  }    Pacific            10           0
%    {'Pacific/Honolulu'              }    Pacific           -10           0
%    {'Pacific/Johnston'              }    Pacific           -10           0
%    {'Pacific/Kiritimati'            }    Pacific            14           0
%    {'Pacific/Kosrae'                }    Pacific            11           0
%    {'Pacific/Kwajalein'             }    Pacific            12           0
%    {'Pacific/Majuro'                }    Pacific            12           0
%    {'Pacific/Marquesas'             }    Pacific          -9.5           0
%    {'Pacific/Midway'                }    Pacific           -11           0
%    {'Pacific/Nauru'                 }    Pacific            12           0
%    {'Pacific/Niue'                  }    Pacific           -11           0
%    {'Pacific/Norfolk'               }    Pacific            11           1
%    {'Pacific/Noumea'                }    Pacific            11           0
%    {'Pacific/Pago_Pago'             }    Pacific           -11           0
%    {'Pacific/Palau'                 }    Pacific             9           0
%    {'Pacific/Pitcairn'              }    Pacific            -8           0
%    {'Pacific/Ponape'                }    Pacific            11           0
%    {'Pacific/Port_Moresby'          }    Pacific            10           0
%    {'Pacific/Rarotonga'             }    Pacific           -10           0
%    {'Pacific/Saipan'                }    Pacific            10           0
%    {'Pacific/Tahiti'                }    Pacific           -10           0
%    {'Pacific/Tarawa'                }    Pacific            12           0
%    {'Pacific/Tongatapu'             }    Pacific            13           0
%    {'Pacific/Truk'                  }    Pacific            10           0
%    {'Pacific/Wake'                  }    Pacific            12           0
%    {'Pacific/Wallis'                }    Pacific            12           0

defval('meeting_day', datetime('today'))

meeting_day.Hour = 0;
meeting_day.TimeZone = '';
base_day = datetime(meeting_day + hours(0:24));

my_day = base_day;
my_day.TimeZone = 'America/Los_Angeles';

their_day = my_day;
their_day.TimeZone = their_timezone;

fprintf('\n')
disp(table(my_day', their_day', 'VariableNames', {'My Time', 'Their Time'}))
